### ISSUE TITLE
How to upload the kaggle key?

### ISSUE THREAD

**Issue by ngoding** [ngoding/bangkit-project#12]
![Screen Shot 2020-04-03 at 09 16 55](https://user-images.githubusercontent.com/15343619/78317243-f46e6180-758b-11ea-88bf-633be6924452.png)

Hey guys, I can't seem to upload the key. I've selected the key and run the next block, but it says can't find the file. Then I tried to run the upload block again after selecting the key but still get the same result.

How do you initiate the upload?

**Comment by Rocksus** [comment]
I've tried to reproduce your error and the kaggle.json was uploaded successfully. Maybe try reopening the page? (refresh the instance)

**Comment by ngoding** [comment]
Oh yeah, it works now, Thanks!
