### ISSUE TITLE
Error encountered while parsing file (Feature extraction)

### ISSUE THREAD

**Issue by ngoding** [ngoding/bangkit-project#13]
Hey @LaodeMFauzan,  I've got a few errors here. Did you get this error too?
![Screen Shot 2020-04-03 at 10 00 30](https://user-images.githubusercontent.com/15343619/78319744-fa674100-7591-11ea-9498-525f3d51b2e5.png)

**Comment by ngoding** [comment]
I've commented the exception part. Here's the error:
    517 
    518     if as_index and x.min() < 0:
--> 519         raise ValueError("index can't contain negative values")
    520 
    521     # Converting the array with `tolist` seems to improve performance

ValueError: index can't contain negative values

**Comment by LaodeMFauzan** [comment]
![image](https://user-images.githubusercontent.com/17470582/78325307-761cba00-75a1-11ea-839f-b80a2e2a6af8.png)

I got the error too, but in the end, it successfully extracts the features from all the files. 

![image](https://user-images.githubusercontent.com/17470582/78325383-a2383b00-75a1-11ea-8ac3-6ba1a9c53106.png)

**Comment by ngoding** [comment]
I think that might be the reason. Some file cannot be extracted so our data isn't balanced. Do you know what might have caused the "ValueError: index can't contain negative values" error?

**Comment by ngoding** [comment]
60 Files aren't converted. I'm trying to fix it now

**Comment by LaodeMFauzan** [comment]
@ngoding sorry for the late reply. How is the fix going?

**Comment by Rocksus** [comment]
@LaodeMFauzan, can you explain what pad_width is being used for in the function? I'm seeing that the negative values are coming from the pad_width

**Comment by LaodeMFauzan** [comment]
@Rocksus  Padding is a process to add values to a time-domain signal to increase its length. Pad_width is a variable used to determine how long the additional value. That's what I understand from reading several articles:
* http://practicalcryptography.com/miscellaneous/machine-learning/guide-mel-frequency-cepstral-coefficients-mfccs/  
* https://www.bitweenie.com/listings/fft-zero-padding/

**Comment by Rocksus** [comment]
@LaodeMFauzan ahh i see, so in the case of a negative pad_width can we just trim the audio instead?

**Comment by ngoding** [comment]
Hi, From my understanding, then the padding tried to add padding in front of the audio while it should be in the end?

**Comment by LaodeMFauzan** [comment]
@Rocksus  we can do that, because from what I understand most of the error parsing coming from file with length more than 20s. Max pad length 862 is corresponding with an audio file with 20s length. 
@ngoding I think the padding is already placed at the end.  The problem is at the length of the file. 
I'll try to change the line of librosa.load to this:
audio, sample_rate = librosa.load(file_name, res_type='kaiser_fast', duration=20) 

turns out adding that one line solves the problem. 

Also, the kaiser_fast type is used for the faster resampling method.
