### ISSUE TITLE
Importing Kaggle Dataset to Google Collab

### ISSUE THREAD

**Issue by Rocksus** [ngoding/bangkit-project#2]
Our [audio dataset](https://www.kaggle.com/vbookshelf/respiratory-sound-database) is quite large (2GB), is there any way to import the data from Kaggle directly to google collab without bloating the repository?

**Comment by ngoding** [comment]
Have you solved this issue? Does your pull request works?

**Comment by Rocksus** [comment]
Tested and it's working fine, closing this issue.
