### ISSUE TITLE
Keep Google Collab Persistent

### ISSUE THREAD

**Issue by Rocksus** [ngoding/bangkit-project#3]
After trying to run the google collab from the repo notebook, it seems that it will drop the processed lines after a page refresh and needs to be re-run to obtain the desired output.
Referring to [this stackoverflow discussion](https://stackoverflow.com/questions/50111729/how-to-make-data-persistent-in-google-colab-using-github-or-google-drive), I think there's a better way of importing the notebook.

**Comment by ngoding** [comment]
Hi, I think that's just how Jupyter notebook works. On local, you will lose all the processed tab if you close the notebook tab. So I think for us to efficiently work on this one, we have to be mindful not to close the tab, or else it will take some time for the notebook to run and initiate everything. I'll make sure again about this tomorrow morning.

**Comment by Rocksus** [comment]
Ah okay, I see. So we have to store the trained model in the repo and load that up for future testing?
